spring.application.name=springboot-mall
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jackson.time-zone=GMT+8
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

# JWT
jwt.expiration-ms=86400000

# Google OAuth2
spring.security.oauth2.client.registration.google.scope=email,profile
